export const MORE_BANDS = [
  ['easy', ['bird', 'horse', 'cow', 'pig', 'mouse', 'egg', 'cheese', 'salt', 'sugar', 'rice', 'soup', 'meat', 'orange', 'banana', 'lemon', 'coffee', 'tea', 'table', 'chair', 'bed', 'window', 'car', 'train', 'boat', 'shoe', 'shirt', 'hat', 'bag', 'head', 'foot', 'ear', 'nose', 'mouth', 'tooth', 'hair', 'snow', 'wind', 'moon', 'star', 'mountain']],
  ['medium', ['river', 'lake', 'forest', 'garden', 'field', 'village', 'kitchen', 'pocket', 'belt', 'glove', 'sock', 'skirt', 'coat', 'blanket', 'carpet', 'curtain', 'fork', 'plate', 'bottle', 'cup', 'soap', 'comb', 'scissors', 'brush', 'wheel', 'roof', 'wall', 'fence', 'stone', 'sand', 'beach', 'leaf', 'branch', 'seed', 'onion', 'garlic', 'carrot', 'cucumber', 'rabbit', 'butterfly']],
  ['hard', ['badger', 'otter', 'weasel', 'beaver', 'bat', 'woodpecker', 'swallow', 'owl', 'stork', 'heron', 'dragonfly', 'grasshopper', 'beetle', 'caterpillar', 'snail', 'slug', 'earthworm', 'leech', 'tadpole', 'toad', 'pinecone', 'birch', 'willow', 'ash-tree', 'reed', 'clover', 'dandelion', 'burdock', 'sorrel', 'yarrow', 'chisel', 'awl', 'mallet', 'sickle', 'scythe', 'rake', 'whetstone', 'bellows', 'spindle', 'spool']],
];

// Each column follows MORE_BANDS: easy, medium, hard. Translations and bands need native-speaker review.
export const MORE_WORDS = {
  en: 'bird|horse|cow|pig|mouse|egg|cheese|salt|sugar|rice|soup|meat|orange|banana|lemon|coffee|tea|table|chair|bed|window|car|train|boat|shoe|shirt|hat|bag|head|foot|ear|nose|mouth|tooth|hair|snow|wind|moon|star|mountain|' +
    'river|lake|forest|garden|field|village|kitchen|pocket|belt|glove|sock|skirt|coat|blanket|carpet|curtain|fork|plate|bottle|cup|soap|comb|scissors|brush|wheel|roof|wall|fence|stone|sand|beach|leaf|branch|seed|onion|garlic|carrot|cucumber|rabbit|butterfly|' +
    'badger|otter|weasel|beaver|bat|woodpecker|swallow|owl|stork|heron|dragonfly|grasshopper|beetle|caterpillar|snail|slug|earthworm|leech|tadpole|toad|pinecone|birch|willow|ash tree|reed|clover|dandelion|burdock|sorrel|yarrow|chisel|awl|mallet|sickle|scythe|rake|whetstone|bellows|spindle|spool',
  es: 'pájaro|caballo|vaca|cerdo|ratón|huevo|queso|sal|azúcar|arroz|sopa|carne|naranja|plátano|limón|café|té|mesa|silla|cama|ventana|coche|tren|barca|zapato|camisa|sombrero|bolsa|cabeza|pie|oreja|nariz|boca|diente|pelo|nieve|viento|luna|estrella|montaña|' +
    'río|lago|bosque|jardín|campo|pueblo|cocina|bolsillo|cinturón|guante|calcetín|falda|abrigo|manta|alfombra|cortina|tenedor|plato|botella|taza|jabón|peine|tijeras|cepillo|rueda|tejado|pared|valla|piedra|arena|playa|hoja|rama|semilla|cebolla|ajo|zanahoria|pepino|conejo|mariposa|' +
    'tejón|nutria|comadreja|castor|murciélago|pájaro carpintero|golondrina|búho|cigüeña|garza|libélula|saltamontes|escarabajo|oruga|caracol|babosa|lombriz de tierra|sanguijuela|renacuajo|sapo|piña de pino|abedul|sauce|fresno|carrizo|trébol|diente de león|bardana|acedera|milenrama|cincel|lezna|mazo|hoz|guadaña|rastrillo|piedra de afilar|fuelle|huso|carrete',
  fr: 'oiseau|cheval|vache|cochon|souris|œuf|fromage|sel|sucre|riz|soupe|viande|orange|banane|citron|café|thé|table|chaise|lit|fenêtre|voiture|train|bateau|chaussure|chemise|chapeau|sac|tête|pied|oreille|nez|bouche|dent|cheveux|neige|vent|lune|étoile|montagne|' +
    'rivière|lac|forêt|jardin|champ|village|cuisine|poche|ceinture|gant|chaussette|jupe|manteau|couverture|tapis|rideau|fourchette|assiette|bouteille|tasse|savon|peigne|ciseaux|brosse|roue|toit|mur|clôture|pierre|sable|plage|feuille|branche|graine|oignon|ail|carotte|concombre|lapin|papillon|' +
    'blaireau|loutre|belette|castor|chauve-souris|pic|hirondelle|hibou|cigogne|héron|libellule|sauterelle|coléoptère|chenille|escargot|limace|ver de terre|sangsue|têtard|crapaud|pomme de pin|bouleau|saule|frêne|roseau|trèfle|pissenlit|bardane|oseille|achillée millefeuille|ciseau à bois|alêne|maillet|faucille|faux|râteau|pierre à aiguiser|soufflet|fuseau|bobine',
  de: 'Vogel|Pferd|Kuh|Schwein|Maus|Ei|Käse|Salz|Zucker|Reis|Suppe|Fleisch|Orange|Banane|Zitrone|Kaffee|Tee|Tisch|Stuhl|Bett|Fenster|Auto|Zug|Boot|Schuh|Hemd|Hut|Tasche|Kopf|Fuß|Ohr|Nase|Mund|Zahn|Haar|Schnee|Wind|Mond|Stern|Berg|' +
    'Fluss|See|Wald|Garten|Feld|Dorf|Küche|Hosentasche|Gürtel|Handschuh|Socke|Rock|Mantel|Decke|Teppich|Vorhang|Gabel|Teller|Flasche|Tasse|Seife|Kamm|Schere|Bürste|Rad|Dach|Wand|Zaun|Stein|Sand|Strand|Blatt|Ast|Samen|Zwiebel|Knoblauch|Karotte|Gurke|Kaninchen|Schmetterling|' +
    'Dachs|Fischotter|Wiesel|Biber|Fledermaus|Specht|Schwalbe|Eule|Storch|Reiher|Libelle|Heuschrecke|Käfer|Raupe|Schnecke|Nacktschnecke|Regenwurm|Blutegel|Kaulquappe|Kröte|Kiefernzapfen|Birke|Weide|Esche|Schilf|Klee|Löwenzahn|Klette|Sauerampfer|Schafgarbe|Meißel|Ahle|Holzhammer|Sichel|Sense|Rechen|Wetzstein|Blasebalg|Spindel|Spule',
  it: 'uccello|cavallo|mucca|maiale|topo|uovo|formaggio|sale|zucchero|riso|zuppa|carne|arancia|banana|limone|caffè|tè|tavolo|sedia|letto|finestra|automobile|treno|barca|scarpa|camicia|cappello|borsa|testa|piede|orecchio|naso|bocca|dente|capelli|neve|vento|luna|stella|montagna|' +
    'fiume|lago|foresta|giardino|campo|villaggio|cucina|tasca|cintura|guanto|calzino|gonna|cappotto|coperta|tappeto|tenda|forchetta|piatto|bottiglia|tazza|sapone|pettine|forbici|spazzola|ruota|tetto|muro|recinto|pietra|sabbia|spiaggia|foglia|ramo|seme|cipolla|aglio|carota|cetriolo|coniglio|farfalla|' +
    'tasso|lontra|donnola|castoro|pipistrello|picchio|rondine|gufo|cicogna|airone|libellula|cavalletta|coleottero|bruco|chiocciola|limaccia|lombrico|sanguisuga|girino|rospo|pigna|betulla|salice|frassino|canna palustre|trifoglio|tarassaco|bardana|acetosa|achillea millefoglie|scalpello|lesina|mazzuolo|falcetto|falce fienaia|rastrello|pietra per affilare|mantice|fuso|rocchetto',
  pt: 'pássaro|cavalo|vaca|porco|rato|ovo|queijo|sal|açúcar|arroz|sopa|carne|laranja|banana|limão|café|chá|mesa|cadeira|cama|janela|carro|trem|barco|sapato|camisa|chapéu|bolsa|cabeça|pé|orelha|nariz|boca|dente|cabelo|neve|vento|lua|estrela|montanha|' +
    'rio|lago|floresta|jardim|campo|aldeia|cozinha|bolso|cinto|luva|meia|saia|casaco|cobertor|tapete|cortina|garfo|prato|garrafa|xícara|sabão|pente|tesoura|escova|roda|telhado|parede|cerca|pedra|areia|praia|folha|galho|semente|cebola|alho|cenoura|pepino|coelho|borboleta|' +
    'texugo|lontra|doninha|castor|morcego|pica-pau|andorinha|coruja|cegonha|garça|libélula|gafanhoto|besouro|lagarta|caracol|lesma|minhoca|sanguessuga|girino|sapo|pinha|bétula|salgueiro|freixo|caniço|trevo|dente-de-leão|bardana|azeda|milefólio|formão|sovela|maço de madeira|foice de mão|gadanha|ancinho|pedra de amolar|fole|fuso|carretel',
  nl: 'vogel|paard|koe|varken|muis|ei|kaas|zout|suiker|rijst|soep|vlees|sinaasappel|banaan|citroen|koffie|thee|tafel|stoel|bed|raam|auto|trein|boot|schoen|overhemd|hoed|tas|hoofd|voet|oor|neus|mond|tand|haar|sneeuw|wind|maan|ster|berg|' +
    'rivier|meer|bos|tuin|veld|dorp|keuken|broekzak|riem|handschoen|sok|rok|jas|deken|tapijt|gordijn|vork|bord|fles|kopje|zeep|kam|schaar|borstel|wiel|dak|muur|hek|steen|zand|strand|blad|tak|zaad|ui|knoflook|wortel|komkommer|konijn|vlinder|' +
    'das|otter|wezel|bever|vleermuis|specht|zwaluw|uil|ooievaar|reiger|libel|sprinkhaan|kever|rups|huisjesslak|naaktslak|regenworm|bloedzuiger|kikkervisje|pad|dennenappel|berk|wilg|es|riet|klaver|paardenbloem|klit|zuring|duizendblad|beitel|priem|houten hamer|sikkel|zeis|hark|wetsteen|blaasbalg|spintol|klos',
  sv: 'fågel|häst|ko|gris|mus|ägg|ost|salt|socker|ris|soppa|kött|apelsin|banan|citron|kaffe|te|bord|stol|säng|fönster|bil|tåg|båt|sko|skjorta|hatt|väska|huvud|fot|öra|näsa|mun|tand|hår|snö|vind|måne|stjärna|berg|' +
    'flod|sjö|skog|trädgård|fält|by|kök|ficka|bälte|handske|strumpa|kjol|kappa|filt|matta|gardin|gaffel|tallrik|flaska|kopp|tvål|kam|sax|borste|hjul|yttertak|vägg|staket|sten|sand|sandstrand|blad|gren|frö|lök|vitlök|morot|gurka|kanin|fjäril|' +
    'grävling|utter|vessla|bäver|fladdermus|hackspett|svala|uggla|stork|häger|trollslända|gräshoppa|skalbagge|fjärilslarv|snäcka|snigel|daggmask|igel|grodyngel|padda|tallkotte|björk|pil|ask|vass|klöver|maskros|kardborre|ängssyra|rölleka|stämjärn|syl|träklubba|skära|lie|kratta|brynsten|bälg|slända|trådrulle',
  pl: 'ptak|koń|krowa|świnia|mysz|jajko|ser|sól|cukier|ryż|zupa|mięso|pomarańcza|banan|cytryna|kawa|herbata|stół|krzesło|łóżko|okno|samochód|pociąg|łódź|but|koszula|kapelusz|torba|głowa|stopa|ucho|nos|usta|ząb|włosy|śnieg|wiatr|księżyc|gwiazda|góra|' +
    'rzeka|jezioro|las|ogród|pole|wieś|kuchnia|kieszeń|pasek|rękawiczka|skarpetka|spódnica|płaszcz|koc|dywan|zasłona|widelec|talerz|butelka|filiżanka|mydło|grzebień|nożyczki|szczotka|koło|dach|ściana|płot|kamień|piasek|plaża|liść|gałąź|nasiono|cebula|czosnek|marchew|ogórek|królik|motyl|' +
    'borsuk|wydra|łasica|bóbr|nietoperz|dzięcioł|jaskółka|sowa|bocian|czapla|ważka|konik polny|chrząszcz|gąsienica|ślimak muszlowy|ślimak nagi|dżdżownica|pijawka|kijanka|ropucha|szyszka sosnowa|brzoza|wierzba|jesion|trzcina|koniczyna|mniszek lekarski|łopian|szczaw|krwawnik|dłuto|szydło|drewniany młotek|sierp|kosa|grabie|osełka|miech|wrzeciono|szpulka',
  ru: 'птица|лошадь|корова|свинья|мышь|яйцо|сыр|соль|сахар|рис|суп|мясо|апельсин|банан|лимон|кофе|чай|стол|стул|кровать|окно|машина|поезд|лодка|ботинок|рубашка|шляпа|сумка|голова|ступня|ухо|нос|рот|зуб|волосы|снег|ветер|луна|звезда|гора|' +
    'река|озеро|лес|сад|поле|деревня|кухня|карман|ремень|перчатка|носок|юбка|пальто|одеяло|ковёр|занавеска|вилка|тарелка|бутылка|чашка|мыло|расчёска|ножницы|щётка|колесо|крыша|стена|забор|камень|песок|пляж|лист|ветка|семя|лук|чеснок|морковь|огурец|кролик|бабочка|' +
    'барсук|выдра|ласка|бобр|летучая мышь|дятел|ласточка|сова|аист|цапля|стрекоза|кузнечик|жук|гусеница|улитка|слизень|дождевой червь|пиявка|головастик|жаба|сосновая шишка|берёза|ива|ясень|тростник|клевер|одуванчик|лопух|щавель|тысячелистник|стамеска|шило|киянка|серп|коса|грабли|точильный камень|кузнечные мехи|веретено|катушка',
  uk: 'птах|кінь|корова|свиня|миша|яйце|сир|сіль|цукор|рис|суп|м’ясо|апельсин|банан|лимон|кава|чай|стіл|стілець|ліжко|вікно|машина|поїзд|човен|черевик|сорочка|капелюх|сумка|голова|ступня|вухо|ніс|рот|зуб|волосся|сніг|вітер|місяць|зірка|гора|' +
    'річка|озеро|ліс|сад|поле|село|кухня|кишеня|ремінь|рукавичка|шкарпетка|спідниця|пальто|ковдра|килим|завіса|виделка|тарілка|пляшка|чашка|мило|гребінець|ножиці|щітка|колесо|дах|стіна|паркан|камінь|пісок|пляж|листок|гілка|насінина|цибуля|часник|морква|огірок|кріль|метелик|' +
    'борсук|видра|ласка|бобер|кажан|дятел|ластівка|сова|лелека|чапля|бабка|коник|жук|гусінь|равлик|слимак|дощовий черв’як|п’явка|пуголовок|ропуха|соснова шишка|береза|верба|ясен|очерет|конюшина|кульбаба|лопух|щавель|деревій|стамеска|шило|киянка|серп|коса|граблі|точильний камінь|ковальський міх|веретено|котушка',
  fi: 'lintu|hevonen|lehmä|sika|hiiri|muna|juusto|suola|sokeri|riisi|keitto|liha|appelsiini|banaani|sitruuna|kahvi|tee|pöytä|tuoli|sänky|ikkuna|auto|juna|vene|kenkä|paita|hattu|laukku|pää|jalkaterä|korva|nenä|suu|hammas|hiukset|lumi|tuuli|kuu|tähti|vuori|' +
    'joki|järvi|metsä|puutarha|pelto|kylä|keittiö|tasku|vyö|käsine|sukka|hame|takki|peitto|matto|verho|haarukka|lautanen|pullo|kuppi|saippua|kampa|sakset|harja|pyörä|vesikatto|seinä|aita|kivi|hiekka|hiekkaranta|lehti|oksa|siemen|sipuli|valkosipuli|porkkana|kurkku|kani|perhonen|' +
    'mäyrä|saukko|lumikko|majava|lepakko|tikka|pääskynen|pöllö|kattohaikara|harmaahaikara|sudenkorento|heinäsirkka|kovakuoriainen|toukka|kotilo|etana|kastemato|iilimato|nuijapää|rupikonna|männynkäpy|koivu|paju|saarni|ruoko|apila|voikukka|takiainen|suolaheinä|siankärsämö|taltta|naskali|puunuija|sirppi|viikate|harava|hiomakivi|palkeet|värttinä|lankarulla',
  el: 'πουλί|άλογο|αγελάδα|γουρούνι|ποντίκι|αυγό|τυρί|αλάτι|ζάχαρη|ρύζι|σούπα|κρέας|πορτοκάλι|μπανάνα|λεμόνι|καφές|τσάι|τραπέζι|καρέκλα|κρεβάτι|παράθυρο|αυτοκίνητο|τρένο|βάρκα|παπούτσι|πουκάμισο|καπέλο|τσάντα|κεφάλι|πέλμα|αυτί|μύτη|στόμα|δόντι|μαλλιά|χιόνι|άνεμος|φεγγάρι|αστέρι|βουνό|' +
    'ποτάμι|λίμνη|δάσος|κήπος|χωράφι|χωριό|κουζίνα|τσέπη|ζώνη|γάντι|κάλτσα|φούστα|παλτό|κουβέρτα|χαλί|κουρτίνα|πιρούνι|πιάτο|μπουκάλι|φλιτζάνι|σαπούνι|χτένα|ψαλίδι|βούρτσα|τροχός|στέγη|τοίχος|φράχτης|πέτρα|άμμος|παραλία|φύλλο|κλαδί|σπόρος|κρεμμύδι|σκόρδο|καρότο|αγγούρι|κουνέλι|πεταλούδα|' +
    'ασβός|βίδρα|νυφίτσα|κάστορας|νυχτερίδα|δρυοκολάπτης|χελιδόνι|κουκουβάγια|πελαργός|ερωδιός|λιβελούλα|ακρίδα|σκαθάρι|κάμπια|σαλιγκάρι|γυμνοσάλιαγκας|γαιοσκώληκας|βδέλλα|γυρίνος|φρύνος|κουκουνάρι|σημύδα|ιτιά|μελιά|καλάμι|τριφύλλι|πικραλίδα|κολλιτσίδα|λάπαθο|αχιλλέα|σμίλη|σουβλί|ξύλινο σφυρί|δρεπάνι|κόσα|τσουγκράνα|ακονόπετρα|φυσερό|αδράχτι|καρούλι',
  hy: 'թռչուն|ձի|կով|խոզ|մուկ|ձու|պանիր|աղ|շաքար|բրինձ|ապուր|միս|նարինջ|բանան|կիտրոն|սուրճ|թեյ|սեղան|աթոռ|մահճակալ|պատուհան|մեքենա|գնացք|նավակ|կոշիկ|վերնաշապիկ|գլխարկ|պայուսակ|գլուխ|ոտնաթաթ|ականջ|քիթ|բերան|ատամ|մազեր|ձյուն|քամի|լուսին|աստղ|լեռ|' +
    'գետ|լիճ|անտառ|այգի|դաշտ|գյուղ|խոհանոց|գրպան|գոտի|ձեռնոց|գուլպա|կիսաշրջազգեստ|վերարկու|վերմակ|գորգ|վարագույր|պատառաքաղ|ափսե|շիշ|բաժակ|օճառ|սանր|մկրատ|խոզանակ|անիվ|տանիք|պատ|ցանկապատ|քար|ավազ|լողափ|տերև|ճյուղ|սերմ|սոխ|սխտոր|գազար|վարունգ|ճագար|թիթեռ|' +
    'փորսուղ|ջրասամույր|աքիս|կուղբ|չղջիկ|փայտփորիկ|ծիծեռնակ|բու|արագիլ|տառեղ|ճպուռ|մորեխ|բզեզ|թրթուր|խխունջ|մերկախխունջ|անձրևորդ|տզրուկ|շերեփուկ|դոդոշ|սոճու կոն|կեչի|ուռենի|հացենի|եղեգ|երեքնուկ|խատուտիկ|կռատուկ|ավելուկ|հազարատերևուկ|դուր|բիզ|փայտե մուրճ|մանգաղ|գերանդի|փոցխ|հեսան|փուքս|իլիկ|կոճ',
  ka: 'ჩიტი|ცხენი|ძროხა|ღორი|თაგვი|კვერცხი|ყველი|მარილი|შაქარი|ბრინჯი|სუპი|ხორცი|ფორთოხალი|ბანანი|ლიმონი|ყავა|ჩაი|მაგიდა|სკამი|საწოლი|ფანჯარა|მანქანა|მატარებელი|ნავი|ფეხსაცმელი|პერანგი|ქუდი|ჩანთა|თავი|ტერფი|ყური|ცხვირი|პირი|კბილი|თმა|თოვლი|ქარი|მთვარე|ვარსკვლავი|მთა|' +
    'მდინარე|ტბა|ტყე|ბაღი|მინდორი|სოფელი|სამზარეულო|ჯიბე|ქამარი|ხელთათმანი|წინდა|ქვედაკაბა|პალტო|საბანი|ხალიჩა|ფარდა|ჩანგალი|თეფში|ბოთლი|ფინჯანი|საპონი|სავარცხელი|მაკრატელი|ჯაგრისი|ბორბალი|სახურავი|კედელი|ღობე|ქვა|ქვიშა|პლაჟი|ფოთოლი|ტოტი|თესლი|ხახვი|ნიორი|სტაფილო|კიტრი|ბოცვერი|პეპელა|' +
    'მაჩვი|წავი|დედოფალა|თახვი|ღამურა|კოდალა|მერცხალი|ბუ|ყარყატი|ყანჩა|ნემსიყლაპია|კალია|ხოჭო|მუხლუხო|ლოკოკინა|ლოქორა|წვიმის ჭია|წურბელა|თავკომბალა|გომბეშო|გირჩი|არყი|ტირიფი|იფანი|ლერწამი|სამყურა|ბაბუაწვერა|ოროვანდი|მჟაუნა|ფარსმანდუკი|სატეხი|სადგისი|ხის ჩაქუჩი|ნამგალი|ცელი|ფოცხი|სალესი ქვა|საბერველი|თითისტარი|კოჭა',
  ja: '鳥|馬|牛|豚|ねずみ|卵|チーズ|塩|砂糖|米|スープ|肉|オレンジ|バナナ|レモン|コーヒー|お茶|テーブル|椅子|ベッド|窓|車|電車|ボート|靴|シャツ|帽子|かばん|頭|足|耳|鼻|口|歯|髪|雪|風|月|星|山|' +
    '川|湖|森|庭|畑|村|台所|ポケット|ベルト|手袋|靴下|スカート|コート|毛布|じゅうたん|カーテン|フォーク|皿|瓶|カップ|石鹸|くし|はさみ|ブラシ|車輪|屋根|壁|柵|石|砂|砂浜|葉|枝|種|玉ねぎ|にんにく|にんじん|きゅうり|うさぎ|蝶|' +
    'アナグマ|カワウソ|イタチ|ビーバー|コウモリ|キツツキ|ツバメ|フクロウ|コウノトリ|サギ|トンボ|バッタ|甲虫|毛虫|カタツムリ|ナメクジ|ミミズ|ヒル|オタマジャクシ|ヒキガエル|松ぼっくり|白樺|柳|トネリコ|葦|クローバー|タンポポ|ゴボウ|スイバ|ノコギリソウ|のみ|きり|木槌|鎌|大鎌|熊手|砥石|ふいご|紡錘|糸巻き',
  cs: 'pták|kůň|kráva|prase|myš|vejce|sýr|sůl|cukr|rýže|polévka|maso|pomeranč|banán|citron|káva|čaj|stůl|židle|postel|okno|auto|vlak|loďka|bota|košile|klobouk|taška|hlava|chodidlo|ucho|nos|ústa|zub|vlasy|sníh|vítr|měsíc|hvězda|hora|' +
    'řeka|jezero|les|zahrada|pole|vesnice|kuchyně|kapsa|opasek|rukavice|ponožka|sukně|kabát|přikrývka|koberec|záclona|vidlička|talíř|láhev|šálek|mýdlo|hřeben|nůžky|kartáč|kolo|střecha|zeď|plot|kámen|písek|pláž|list|větev|semeno|cibule|česnek|mrkev|okurka|králík|motýl|' +
    'jezevec|vydra|lasice|bobr|netopýr|datel|vlaštovka|sova|čáp|volavka|vážka|kobylka|brouk|housenka|hlemýžď|slimák|žížala|pijavice|pulec|ropucha|borová šiška|bříza|vrba|jasan|rákos|jetel|pampeliška|lopuch|šťovík|řebříček|dláto|šídlo|dřevěná palice|srp|kosa|hrábě|brousek|měch|vřeteno|cívka',
  ro: 'pasăre|cal|vacă|porc|șoarece|ou|brânză|sare|zahăr|orez|supă|carne|portocală|banană|lămâie|cafea|ceai|masă|scaun|pat|fereastră|mașină|tren|barcă|pantof|cămașă|pălărie|geantă|cap|laba piciorului|ureche|nas|gură|dinte|păr|zăpadă|vânt|lună|stea|munte|' +
    'râu|lac|pădure|grădină|câmp|sat|bucătărie|buzunar|curea|mănușă|șosetă|fustă|palton|pătură|covor|perdea|furculiță|farfurie|sticlă|ceașcă|săpun|pieptene|foarfecă|perie|roată|acoperiș|perete|gard|piatră|nisip|plajă|frunză|creangă|sămânță|ceapă|usturoi|morcov|castravete|iepure|fluture|' +
    'bursuc|vidră|nevăstuică|castor|liliac|ciocănitoare|rândunică|bufniță|barză|stârc|libelulă|lăcustă|gândac|omidă|melc cu cochilie|limax|râmă|lipitoare|mormoloc|broască râioasă|con de pin|mesteacăn|salcie|frasin|stuf|trifoi|păpădie|brusture|măcriș|coada-șoricelului|daltă|sulă|mai de lemn|seceră|coasă|greblă|cute|foale|fus|mosor',
  hu: 'madár|ló|tehén|disznó|egér|tojás|sajt|só|cukor|rizs|leves|hús|narancs|banán|citrom|kávé|tea|asztal|szék|ágy|ablak|autó|vonat|csónak|cipő|ing|kalap|táska|fej|lábfej|fül|orr|száj|fog|haj|hó|szél|hold|csillag|hegy|' +
    'folyó|tó|erdő|kert|mező|falu|konyha|zseb|öv|kesztyű|zokni|szoknya|kabát|takaró|szőnyeg|függöny|villa|tányér|palack|csésze|szappan|fésű|olló|kefe|kerék|tető|fal|kerítés|kő|homok|homokos part|levél|ág|mag|hagyma|fokhagyma|sárgarépa|uborka|üregi nyúl|pillangó|' +
    'borz|vidra|menyét|hód|denevér|harkály|fecske|bagoly|gólya|gém|szitakötő|szöcske|bogár|hernyó|házas csiga|meztelencsiga|földigiliszta|pióca|ebihal|varangy|fenyőtoboz|nyírfa|fűzfa|kőrisfa|nád|lóhere|pitypang|bojtorján|sóska|cickafark|véső|ár|fakalapács|sarló|kasza|gereblye|fenőkő|fújtató|orsó|cérnatekercs',
  da: 'fugl|hest|ko|gris|mus|æg|ost|salt|sukker|ris|suppe|kød|appelsin|banan|citron|kaffe|te|bord|stol|seng|vindue|bil|tog|båd|sko|skjorte|hat|taske|hoved|fod|øre|næse|mund|tand|hår|sne|vind|måne|stjerne|bjerg|' +
    'flod|sø|skov|have|mark|landsby|køkken|lomme|bælte|handske|sok|nederdel|frakke|tæppe|gulvtæppe|gardin|gaffel|tallerken|flaske|kop|sæbe|kam|saks|børste|hjul|tag|væg|hegn|sten|sand|strand|blad|gren|frø|løg|hvidløg|gulerod|agurk|kanin|sommerfugl|' +
    'grævling|odder|væsel|bæver|flagermus|spætte|svale|ugle|stork|hejre|guldsmed|græshoppe|bille|sommerfuglelarve|snegl med hus|nøgensnegl|regnorm|igle|haletudse|tudse|fyrrekogle|birk|pil|ask|tagrør|kløver|mælkebøtte|burre|syre|røllike|mejsel|syl|trækølle|segl|le|rive|hvæssesten|blæsebælg|ten|trådspole',
  no: 'fugl|hest|ku|gris|mus|egg|ost|salt|sukker|ris|suppe|kjøtt|appelsin|banan|sitron|kaffe|te|bord|stol|seng|vindu|bil|tog|båt|sko|skjorte|hatt|veske|hode|fot|øre|nese|munn|tann|hår|snø|vind|måne|stjerne|fjell|' +
    'elv|innsjø|skog|hage|åker|landsby|kjøkken|lomme|belte|hanske|sokk|skjørt|kåpe|pledd|gulvteppe|gardin|gaffel|tallerken|flaske|kopp|såpe|kam|saks|børste|hjul|yttertak|vegg|gjerde|stein|sand|strand|blad|gren|frø|løk|hvitløk|gulrot|agurk|kanin|sommerfugl|' +
    'grevling|oter|snømus|bever|flaggermus|hakkespett|svale|ugle|stork|hegre|øyenstikker|gresshoppe|bille|sommerfugllarve|snegl med hus|nakensnegl|meitemark|igle|rumpetroll|padde|furukongle|bjørk|pil|ask|takrør|kløver|løvetann|borre|engsyre|ryllik|meisel|syl|treklubbe|sigd|ljå|rive|brynestein|blåsebelg|håndtein|trådsnelle',
  tr: 'kuş|at|inek|domuz|fare|yumurta|peynir|tuz|şeker|pirinç|çorba|et|portakal|muz|limon|kahve|çay|masa|sandalye|yatak|pencere|araba|tren|kayık|ayakkabı|gömlek|şapka|çanta|baş|ayak|kulak|burun|ağız|diş|saç|kar|rüzgâr|ay|yıldız|dağ|' +
    'nehir|göl|orman|bahçe|tarla|köy|mutfak|cep|kemer|eldiven|çorap|etek|palto|battaniye|halı|perde|çatal|tabak|şişe|fincan|sabun|tarak|makas|fırça|tekerlek|çatı|duvar|çit|taş|kum|plaj|yaprak|dal|tohum|soğan|sarımsak|havuç|salatalık|tavşan|kelebek|' +
    'porsuk|su samuru|gelincik|kunduz|yarasa|ağaçkakan|kırlangıç|baykuş|leylek|balıkçıl|yusufçuk|çekirge|kın kanatlı böcek|tırtıl|salyangoz|sümüklü böcek|toprak solucanı|sülük|iribaş|kara kurbağası|çam kozalağı|huş|söğüt|dişbudak|kamış|yonca|karahindiba|dulavratotu|kuzukulağı|civanperçemi|keski|biz|ahşap tokmak|orak|tırpan|tırmık|bileği taşı|körük|iğ|iplik makarası',
};

export const MORE_ROMANIZATIONS = {
  ru: 'ptitsa|loshad|korova|svinya|mysh|yaytso|syr|sol|sakhar|ris|sup|myaso|apelsin|banan|limon|kofe|chay|stol|stul|krovat|okno|mashina|poezd|lodka|botinok|rubashka|shlyapa|sumka|golova|stupnya|ukho|nos|rot|zub|volosy|sneg|veter|luna|zvezda|gora|' +
    'reka|ozero|les|sad|pole|derevnya|kukhnya|karman|remen|perchatka|nosok|yubka|palto|odeyalo|kovyor|zanaveska|vilka|tarelka|butylka|chashka|mylo|raschyoska|nozhnitsy|shchyotka|koleso|krysha|stena|zabor|kamen|pesok|plyazh|list|vetka|semya|luk|chesnok|morkov|ogurets|krolik|babochka|' +
    'barsuk|vydra|laska|bobr|letuchaya mysh|dyatel|lastochka|sova|aist|tsaplya|strekoza|kuznechik|zhuk|gusenitsa|ulitka|slizen|dozhdevoy cherv|piyavka|golovastik|zhaba|sosnovaya shishka|beryoza|iva|yasen|trostnik|klever|oduvanchik|lopukh|shchavel|tysyachelistnik|stameska|shilo|kiyanka|serp|kosa|grabli|tochilnyy kamen|kuznechnye mekhi|vereteno|katushka',
  uk: 'ptakh|kin|korova|svynya|mysha|yaitse|syr|sil|tsukor|rys|sup|miaso|apelsyn|banan|lymon|kava|chai|stil|stilets|lizhko|vikno|mashyna|poizd|choven|cherevyk|sorochka|kapeliukh|sumka|holova|stupnia|vukho|nis|rot|zub|volossia|snih|viter|misiats|zirka|hora|' +
    'richka|ozero|lis|sad|pole|selo|kukhnia|kyshenia|remin|rukavychka|shkarpetka|spidnytsia|palto|kovdra|kylym|zavisa|vydelka|tarilka|pliashka|chashka|mylo|hrebinets|nozhytsi|shchitka|koleso|dakh|stina|parkan|kamin|pisok|pliazh|lystok|hilka|nasinyna|tsybulia|chasnyk|morkva|ohirok|kril|metelyk|' +
    'borsuk|vydra|laska|bober|kazhan|diatel|lastivka|sova|leleka|chaplia|babka|konyk|zhuk|husin|ravlyk|slymak|doshchovyi cherviak|piavka|puholovok|ropukha|sosnova shyshka|bereza|verba|yasen|ocheret|koniushyna|kulbaba|lopukh|shchavel|derevii|stameska|shylo|kyianka|serp|kosa|hrabli|tochylnyi kamin|kovalskyi mikh|vereteno|kotushka',
  el: 'poulí|álogo|ageláda|gouroúni|pontíki|avgó|tyrí|aláti|záchari|rýzi|soúpa|kréas|portokáli|banána|lemóni|kafés|tsái|trapézi|karékla|kreváti|paráthyro|aftokínito|tréno|várka|papoútsi|poukámiso|kapélo|tsánta|kefáli|pélma|aftí|mýti|stóma|dónti|malliá|chióni|ánemos|fengári|astéri|vounó|' +
    'potámi|límni|dásos|kípos|choráfi|chorió|kouzína|tsépi|zóni|gánti|káltsa|foústa|paltó|kouvérta|chalí|kourtína|piroúni|piáto|boukáli|flitzáni|sapoúni|chténa|psalídi|voúrtsa|trochós|stégi|toíchos|fráchtis|pétra|ámmos|paralía|fýllo|kladí|spóros|kremmýdi|skórdo|karóto|angoúri|kounéli|petaloúda|' +
    'asvós|vídra|nyfítsa|kástoras|nychterída|dryokoláptis|chelidóni|koukouvágia|pelargós|erodiós|liveloúla|akrída|skathári|kámpia|salinkári|gymnosáliankas|gaioskólikas|vdélla|gyrínos|frýnos|koukounári|simýda|itiá|meliá|kalámi|trifýlli|pikralída|kollitsída|lápatho|achilléa|smíli|souvlí|xýlino sfyrí|drepáni|kósa|tsougrána|akonópetra|fyseró|adráchti|karoúli',
  hy: 'trchun|dzi|kov|khoz|muk|dzu|panir|agh|shakar|brindz|apur|mis|narinj|banan|kitron|surch|tey|seghan|ator|mahchakal|patuhan|mekena|gnatsk|navak|koshik|vernashapik|glkhark|payusak|glukh|votnatat|akanj|kit|beran|atam|mazer|dzyun|kami|lusin|astgh|ler|' +
    'get|lich|antar|aygi|dasht|gyugh|khohanots|grpan|goti|dzernots|gulpa|kisashrkazgest|verarku|vermak|gorg|varaguyr|patarakagh|apse|shish|bazhak|ochar|sanr|mkrat|khozanak|aniv|tanik|pat|tsankapat|kar|avaz|loghap|terev|chyugh|serm|sokh|skhtor|gazar|varung|chagar|titer|' +
    'porsugh|jrasamuyr|akis|kughb|chghjik|paytporik|tsitsernak|bu|aragil|taregh|chpur|morekh|bzez|trtur|khkhunj|merkakhkhunj|andzrevord|tzruk|sherepuk|dodosh|sochu kon|kechi|ureni|hatseni|yegheg|yereknuk|khatutik|kratuk|aveluk|hazaraterevuk|dur|biz|payte murch|mangagh|gerandi|potskh|hesan|puks|ilik|koch',
  ka: 'chiti|tskheni|dzrokha|ghori|tagvi|kvertskhi|qveli|marili|shakari|brinji|supi|khortsi|portokhali|banani|limoni|qava|chai|magida|skami|satsoli|panjara|mankana|matarebeli|navi|pekhsatsmeli|perangi|kudi|chanta|tavi|terpi|quri|tskhviri|piri|kbili|tma|tovli|kari|mtvare|varskvlavi|mta|' +
    'mdinare|tba|tqe|baghi|mindori|sopeli|samzareulo|jibe|kamari|kheltatmani|tsinda|kvedakaba|palto|sabani|khalicha|parda|changali|tepshi|botli|pinjani|saponi|savartskheli|makrateli|jagrisi|borbali|sakhuravi|kedeli|ghobe|kva|kvisha|plazhi|potoli|toti|tesli|khakhvi|niori|stapilo|kitri|botsveri|pepela|' +
    'machvi|tsavi|dedopala|takhvi|ghamura|kodala|mertskhali|bu|qarqati|qancha|nemsiqlapia|kalia|khocho|mukhlukho|lokokina|lokora|tsvimis chia|tsurbela|tavkombala|gombesho|girchi|arqi|tiripi|ipani|lertsami|samqura|babuatsvera|orovandi|mzhauna|parsmanduki|satekhi|sadgisi|khis chakuchi|namgali|tseli|potskhi|salesi kva|saberveli|titistari|kocha',
  ja: 'tori|uma|ushi|buta|nezumi|tamago|chīzu|shio|satō|kome|sūpu|niku|orenji|banana|remon|kōhī|ocha|tēburu|isu|beddo|mado|kuruma|densha|bōto|kutsu|shatsu|bōshi|kaban|atama|ashi|mimi|hana|kuchi|ha|kami|yuki|kaze|tsuki|hoshi|yama|' +
    'kawa|mizuumi|mori|niwa|hatake|mura|daidokoro|poketto|beruto|tebukuro|kutsushita|sukāto|kōto|mōfu|jūtan|kāten|fōku|sara|bin|kappu|sekken|kushi|hasami|burashi|sharin|yane|kabe|saku|ishi|suna|sunahama|ha|eda|tane|tamanegi|ninniku|ninjin|kyūri|usagi|chō|' +
    'anaguma|kawauso|itachi|bībā|kōmori|kitsutsuki|tsubame|fukurō|kōnotori|sagi|tonbo|batta|kōchū|kemushi|katatsumuri|namekuji|mimizu|hiru|otamajakushi|hikigaeru|matsubokkuri|shirakaba|yanagi|toneriko|ashi|kurōbā|tanpopo|gobō|suiba|nokogirisō|nomi|kiri|kizuchi|kama|ōgama|kumade|toishi|fuigo|bōsui|itomaki',
};
