export { CONCEPTS } from './vocabulary/index.js';

export const CONFIG = {
  version: '0.7.0',
  referenceLanguages: ['en', 'es', 'ru'],
  defaultLanguages: ['en', 'es', 'fr', 'de', 'it', 'pt', 'sv', 'pl', 'ru', 'uk', 'fi'],
  optionCount: 4,
  maxQuestions: 180,
  timing: { minSecondsPerQuestion: 10 / 3, maxSecondsPerQuestion: 5 },
  adaptive: {
    minimumScreenScore: 2,
    minimumFollowupScore: 2,
    confirmationBands: ['easy', 'easy', 'medium', 'medium', 'medium', 'medium', 'hard', 'hard', 'hard', 'hard'],
  },
  scoring: { correct: 1, incorrect: -1, skipped: 0 },
  ranking: { maxLanguages: 10, minimumQuestions: 10, minimumScore: 2 },
  multilingual: { fractionDigits: 1 },
  charts: { columnsPerStage: 4 },
  stages: [
    { id: 'easy', questionsPerLanguage: 5 },
    { id: 'medium', questionsPerLanguage: 5 },
    { id: 'hard', questionsPerLanguage: 10 },
  ],
};

export const LANGUAGES = {
  en: { family: 'Germanic', native: 'English' },
  es: { family: 'Romance', native: 'Español' },
  fr: { family: 'Romance', native: 'Français' },
  de: { family: 'Germanic', native: 'Deutsch' },
  it: { family: 'Romance', native: 'Italiano' },
  pt: { family: 'Romance', native: 'Português' },
  nl: { family: 'Germanic', native: 'Nederlands' },
  sv: { family: 'Germanic', native: 'Svenska' },
  pl: { family: 'Slavic', native: 'Polski' },
  ru: { family: 'Slavic', native: 'Русский' },
  uk: { family: 'Slavic', native: 'Українська' },
  fi: { family: 'Uralic', native: 'Suomi' },
  el: { family: 'Hellenic', native: 'Ελληνικά' },
  hy: { family: 'Armenian', native: 'Հայերեն' },
  ka: { family: 'Kartvelian', native: 'ქართული' },
  ja: { family: 'Japonic', native: '日本語' },
  cs: { family: 'Slavic', native: 'Čeština' },
  ro: { family: 'Romance', native: 'Română' },
  hu: { family: 'Uralic', native: 'Magyar' },
  da: { family: 'Germanic', native: 'Dansk' },
  no: { family: 'Germanic', native: 'Norsk bokmål' },
  tr: { family: 'Turkic', native: 'Türkçe' },
};

export const COPY = {
  en: {
    appName: 'Multilingual vocabulary',
    footer: 'An exploration of words. Not a fluency test. · Nothing is uploaded or saved.',
    eyebrow: 'A LITTLE LANGUAGE DISCOVERY', title: 'More languages than<br>you might think.',
    intro: 'Discover how far your vocabulary reaches. The questions adapt as you go.',
    short: 'About {min}–{max} minutes', adaptive: 'Up to {count} questions',
    reference: 'My language',
    native: 'Languages to test', nativeHint: 'Your language is left out automatically.', moreLanguages: 'More languages',
    scripts: 'Show Latin-letter readings',
    start: 'Let’s find out', empty: 'Leave at least one language in the test.',
    question: 'QUESTION', upTo: 'UP TO',
    easy: 'Explore', medium: 'Refine', hard: 'Confirm',
    easyLevel: 'Easy', mediumLevel: 'Medium', hardLevel: 'Hard',
    stage: 'Stage', languages: 'languages', questions: 'questions',
    transitionTitle: 'Let’s take a closer look.',
    transitionBody: 'These languages passed the first round. Next: five medium words each, with time reserved for a final check.',
    confirmationTitle: 'One last check.',
    confirmationBody: 'Ten fresh words per language, from familiar to trickier. Let’s see how far you get.',
    continue: 'Continue', meaning: 'Choose the meaning of this word',
    skip: 'I don’t know :(', unknown: 'Skipped',
    exit: 'Finish early', exitConfirm: 'Finish now and see results from the questions you have answered?',
    shortcut: '1–4 to answer · 0 for “I don’t know :(”',
    resultsTitle: 'My languages',
    rankingEmptyTitle: 'No shortlist yet', rankingEmpty: 'No languages cleared the shortlist cutoff this time. All your answers are available in details.',
    rankingIncomplete: 'Not enough answers for the main ranking yet. Your results so far are available in details.',
    rankingDetails: 'Details & all languages', rankingMethod: 'HOW TO READ THE RESULTS',
    rankingMethodBody: 'The card combines all stages, not just the final round. Percentages and bars show correct answers divided by all questions shown, including skips. Skips are still recorded separately from errors. Up to ten languages with enough follow-up answers and a positive result appear; short early samples and weaker results stay in details. Higher percentages come first. Equal rates share a rank, with more questions first, then alphabetical order. These are quiz results, not calibrated proficiency levels.',
    multilingualTitle: 'Multilingual score', multilingualUnit: '1 point = 20/20 in one language', partial: 'Partial result',
    metricTitle: 'ABOUT THE MULTILINGUAL SCORE',
    metricBody: 'Every tested language contributes across all stages: correct answers minus one third of incorrect answers, divided by 20—the length of a complete run in one language. Negative contributions are set to zero, then all languages are added together, including those outside the top ten. Skips add nothing and are not errors. One point means a perfect 20-question run in one language; partial recognition contributes fractions. The guessing discount is a heuristic, not a confidence estimate: adaptive selection and the zero floor can still reward luck. Excluded languages do not count; unfinished or budget-limited runs have less opportunity to contribute. This is a quiz-specific score, not the number of languages you know or a validated fluency measure. Different selections, words, and reading aids affect comparisons.',
    rankingBar: 'Correct answers across all stages',
    correct: 'correct', incorrect: 'incorrect', questionTotal: 'questions shown', skippedLabel: 'skipped', shown: 'Questions recorded: {count}',
    units: { languages: { one: 'language', other: 'languages' }, questions: { one: 'question', other: 'questions' } },
    accuracy: 'Correct answers across all questions', noAnswers: 'No questions recorded',
    breakdown: 'Language by language', unassessed: 'Not assessed',
    chartHint: 'Questions grouped by stage, which can mix difficulties. Dashed placeholders mark unasked questions or stages not reached.',
    stageBreakdown: 'Your three-stage path', notReached: 'Not reached', notAsked: 'Not asked',
    caveat: 'Counts describe this session only. Languages receive different numbers and difficulties of questions, so the chart is not a proficiency ranking. Four-choice guessing averages 25% correct. Skips are not counted as incorrect answers.',
    method: 'HOW QUESTIONS ADAPT',
    methodBody: 'Start with five easy words in each language. Languages showing recognition move on to five medium words, then ten final words: two easy, four medium, four hard. Languages where everything was skipped do not return. We reserve enough questions for a full final round for every language admitted to the second stage. If the budget cannot fit everyone, stronger early results take priority. The test can finish early when no languages qualify. A language left out by the budget, or an unfinished round, is not a failed result.',
    scriptOn: 'Romanization on', scriptOff: 'Romanization off', restart: 'Explore again', review: 'Review the words', yourAnswer: 'Your answer', rightAnswer: 'Meaning',
    languageNames: { en: 'English', es: 'Spanish', fr: 'French', de: 'German', it: 'Italian', pt: 'Portuguese', nl: 'Dutch', sv: 'Swedish', pl: 'Polish', ru: 'Russian', uk: 'Ukrainian', fi: 'Finnish', el: 'Greek', hy: 'Armenian', ka: 'Georgian', ja: 'Japanese', cs: 'Czech', ro: 'Romanian', hu: 'Hungarian', da: 'Danish', no: 'Norwegian', tr: 'Turkish' },
    familyNames: { Germanic: 'Germanic', Romance: 'Romance', Slavic: 'Slavic', Uralic: 'Uralic', Hellenic: 'Hellenic', Armenian: 'Armenian', Kartvelian: 'Kartvelian', Japonic: 'Japonic', Turkic: 'Turkic' },
  },
  es: {
    appName: 'Vocabulario multilingüe',
    footer: 'Una exploración de palabras. No mide la fluidez. · No se sube ni se guarda ningún dato.',
    eyebrow: 'DESCUBRE OTRAS LENGUAS', title: 'Más idiomas de los<br>que te imaginas.',
    intro: 'Descubre hasta dónde llega tu vocabulario. Las preguntas se adaptan a tus respuestas.',
    short: 'Unos {min}–{max} minutos', adaptive: 'Hasta {count} preguntas',
    reference: 'Mi idioma',
    native: 'Idiomas del test', nativeHint: 'Tu idioma se excluye automáticamente.', moreLanguages: 'Más idiomas',
    scripts: 'Mostrar lecturas en letras latinas',
    start: 'Vamos a descubrirlo', empty: 'Deja al menos un idioma para evaluar.',
    question: 'PREGUNTA', upTo: 'HASTA',
    easy: 'Explorar', medium: 'Afinar', hard: 'Confirmar',
    easyLevel: 'Fácil', mediumLevel: 'Intermedio', hardLevel: 'Difícil',
    stage: 'Etapa', languages: 'idiomas', questions: 'preguntas',
    transitionTitle: 'Veamos más de cerca.',
    transitionBody: 'Estos idiomas han superado la primera ronda. Ahora, cinco palabras intermedias por idioma, con tiempo reservado para la comprobación final.',
    confirmationTitle: 'Una última comprobación.',
    confirmationBody: 'Diez palabras nuevas por idioma, de las más familiares a las más difíciles. Veamos hasta dónde llegas.',
    continue: 'Continuar', meaning: 'Elige el significado de esta palabra',
    skip: 'No lo sé :(', unknown: 'Omitida',
    exit: 'Terminar ahora', exitConfirm: '¿Terminar ahora y ver los resultados de las preguntas que has respondido?',
    shortcut: '1–4 para responder · 0 para «No lo sé :(»',
    resultsTitle: 'Mis idiomas',
    rankingEmptyTitle: 'Aún no hay lista final', rankingEmpty: 'Ningún idioma ha alcanzado el mínimo para la lista final esta vez. Todas tus respuestas están en los detalles.',
    rankingIncomplete: 'Aún faltan respuestas para la clasificación principal. Tus resultados hasta ahora están en los detalles.',
    rankingDetails: 'Detalles y todos los idiomas', rankingMethod: 'CÓMO LEER LOS RESULTADOS',
    rankingMethodBody: 'La tarjeta combina todas las etapas, no solo la final. Porcentajes y barras muestran aciertos divididos entre todas las preguntas vistas, incluidas las omisiones. Las omisiones siguen separadas de los errores. Aparecen hasta diez idiomas con suficientes respuestas de seguimiento y un resultado positivo; las muestras pequeñas y los resultados más débiles quedan en los detalles. Se ordenan por porcentaje. Los empates comparten puesto, con más preguntas primero y después por orden alfabético. Son resultados del test, no niveles de dominio calibrados.',
    multilingualTitle: 'Índice multilingüe', multilingualUnit: '1 punto = 20/20 en un idioma', partial: 'Resultado parcial',
    metricTitle: 'SOBRE EL ÍNDICE MULTILINGÜE',
    metricBody: 'Cada idioma aporta sus resultados de todas las etapas: aciertos menos un tercio de los errores, dividido entre 20, la longitud de un recorrido completo. Las contribuciones negativas se dejan en cero y se suman todos los idiomas, no solo los diez primeros. Las omisiones no aportan puntos ni cuentan como errores. Un punto equivale a un recorrido perfecto de 20 preguntas en un idioma; el reconocimiento parcial aporta fracciones. El descuento por azar es una aproximación, no una estimación de confianza: la selección adaptativa y el mínimo de cero aún pueden premiar la suerte. Los idiomas excluidos no cuentan; los recorridos incompletos o limitados por el presupuesto tienen menos oportunidades de sumar. Es un índice de este test, no el número de idiomas que sabes ni una medida validada de fluidez. La selección, las palabras y las ayudas de lectura afectan las comparaciones.',
    rankingBar: 'Aciertos en todas las etapas',
    correct: 'correctas', incorrect: 'incorrectas', questionTotal: 'preguntas vistas', skippedLabel: 'omitidas', shown: 'Preguntas registradas: {count}',
    units: { languages: { one: 'idioma', other: 'idiomas' }, questions: { one: 'pregunta', other: 'preguntas' } },
    accuracy: 'Aciertos sobre todas las preguntas', noAnswers: 'Sin preguntas registradas',
    breakdown: 'Idioma por idioma', unassessed: 'Sin evaluar',
    chartHint: 'Preguntas por etapa, con posibles dificultades distintas. Los huecos discontinuos indican preguntas pendientes o etapas sin explorar.',
    stageBreakdown: 'Tu recorrido en tres etapas', notReached: 'Sin explorar', notAsked: 'Sin preguntar',
    caveat: 'Los resultados describen solo esta sesión. Cada idioma recibe distintas cantidades y dificultades de preguntas; el gráfico no es una clasificación de dominio. Adivinar entre cuatro opciones da un 25 % de aciertos de media. Las omisiones no cuentan como errores.',
    method: 'CÓMO SE ADAPTAN LAS PREGUNTAS',
    methodBody: 'Empezamos con cinco palabras fáciles por idioma. Los idiomas con señales de reconocimiento pasan a cinco palabras intermedias y después a diez finales: dos fáciles, cuatro intermedias y cuatro difíciles. Los idiomas donde se ha omitido todo no vuelven. Reservamos una ronda final completa para cada idioma admitido en la segunda etapa. Si no caben todos en el presupuesto, priorizamos los mejores resultados iniciales. El test termina antes si no quedan candidatos. Un idioma excluido por el presupuesto o una ronda incompleta no equivalen a un fallo.',
    scriptOn: 'Romanización activada', scriptOff: 'Romanización desactivada', restart: 'Explorar de nuevo', review: 'Revisar las palabras', yourAnswer: 'Tu respuesta', rightAnswer: 'Significado',
    languageNames: { en: 'Inglés', es: 'Español', fr: 'Francés', de: 'Alemán', it: 'Italiano', pt: 'Portugués', nl: 'Neerlandés', sv: 'Sueco', pl: 'Polaco', ru: 'Ruso', uk: 'Ucraniano', fi: 'Finés', el: 'Griego', hy: 'Armenio', ka: 'Georgiano', ja: 'Japonés', cs: 'Checo', ro: 'Rumano', hu: 'Húngaro', da: 'Danés', no: 'Noruego', tr: 'Turco' },
    familyNames: { Germanic: 'Germánico', Romance: 'Romance', Slavic: 'Eslavo', Uralic: 'Urálico', Hellenic: 'Helénico', Armenian: 'Armenio', Kartvelian: 'Kartveliano', Japonic: 'Japónico', Turkic: 'Túrquico' },
  },
  ru: {
    appName: 'Слова на разных языках',
    footer: 'Тест на знание слов, а не на уровень языка. · Ответы никуда не отправляются и не сохраняются.',
    eyebrow: 'МАЛЕНЬКОЕ ЯЗЫКОВОЕ ПРИКЛЮЧЕНИЕ', title: 'Больше языков,<br>чем вы думаете.',
    intro: 'Как далеко вас заведут знакомые слова? Вопросы подстроятся под ваши ответы.',
    short: 'Около {min}–{max} мин.', adaptive: 'До {count} вопросов',
    reference: 'Мой язык',
    native: 'Языки теста', nativeHint: 'Ваш язык в тест не входит.', moreLanguages: 'Ещё языки',
    scripts: 'Транслитерация',
    start: 'Начать тест', empty: 'Выберите хотя бы один язык.',
    question: 'ВОПРОС', upTo: 'ДО',
    easy: 'Разминка', medium: 'Посложнее', hard: 'Финал',
    easyLevel: 'Простые слова', mediumLevel: 'Средняя сложность', hardLevel: 'Сложные слова',
    stage: 'Этап', languages: 'языков', questions: 'вопросов',
    transitionTitle: 'Теперь чуть сложнее.',
    transitionBody: 'Эти языки прошли первый этап. Дальше — по пять слов средней сложности. На финальную проверку мы тоже оставили время.',
    confirmationTitle: 'Остался финал.',
    confirmationBody: 'Ещё десять слов на каждом языке: от знакомых до заковыристых. Посмотрим, как далеко вы зайдёте.',
    continue: 'Продолжить', meaning: 'Выберите значение слова',
    skip: 'Не знаю :(', unknown: 'Пропущено',
    exit: 'Закончить тест', exitConfirm: 'Закончить сейчас и посмотреть промежуточные результаты?',
    shortcut: '1–4 — выбрать ответ · 0 — «Не знаю :(»',
    resultsTitle: 'Мои языки',
    rankingEmptyTitle: 'Пока нет результатов', rankingEmpty: 'В этот раз ни один язык не прошёл отбор в итоговый список. Все ответы — в подробностях.',
    rankingIncomplete: 'Для основного списка пока мало ответов. Всё, что уже получилось, — в подробностях.',
    rankingDetails: 'Подробности и все языки', rankingMethod: 'ЧТО ПОКАЗАНО В КАРТОЧКЕ',
    rankingMethodBody: 'В карточке учитываются все этапы, а не только финал. Процент и полоса — это верные ответы из всех показанных вопросов, включая пропуски. При этом пропуски по-прежнему отмечены отдельно от ошибок. Показываем до десяти языков, по которым уже есть достаточно ответов за несколько этапов и положительный результат. Короткие пробы и более слабые результаты остаются в подробностях. Чем выше процент, тем выше место. При равном проценте место общее; сначала идут языки с большим числом вопросов, затем — по алфавиту. Это результаты игры со словами, а не оценка уровня языка.',
    multilingualTitle: 'Индекс полиглота', multilingualUnit: '1 балл — 20 из 20 на одном языке', partial: 'Тест не завершён',
    metricTitle: 'ОБ ИНДЕКСЕ ПОЛИГЛОТА',
    metricBody: 'Каждый язык вносит свой вклад за все этапы: из числа верных ответов вычитаем треть ошибок и делим на 20 — столько вопросов в полном прохождении одного языка. Если получилось меньше нуля, берём ноль. Затем складываем результаты всех языков, не только первой десятки. Пропуски ничего не добавляют и не считаются ошибками. Один балл — это 20 верных ответов из 20 на одном языке; частичное знание даёт доли балла. Поправка на угадывание приблизительная: отбор языков и замена отрицательных значений нулём всё ещё могут наградить за везение. Исключённые языки не учитываются. Если тест закончился раньше или на язык не хватило лимита, возможностей набрать баллы было меньше. Это игровой индекс, а не число языков, которыми вы владеете, и не научная оценка. На результат влияют выбранные языки, сами слова и транслитерация.',
    rankingBar: 'Верные ответы за все этапы',
    correct: 'верно', incorrect: 'неверно', questionTotal: 'всего вопросов', skippedLabel: 'пропущено', shown: 'Пройдено вопросов: {count}',
    units: { languages: { one: 'язык', few: 'языка', many: 'языков', other: 'языка' }, questions: { one: 'вопрос', few: 'вопроса', many: 'вопросов', other: 'вопроса' } },
    accuracy: 'Верные ответы', noAnswers: 'Пока нет вопросов',
    breakdown: 'Результаты по языкам', unassessed: 'Не было вопросов',
    chartHint: 'Каждая клетка — один вопрос. Вопросы сгруппированы по этапам. Пунктиром отмечено то, до чего тест не дошёл.',
    stageBreakdown: 'Как прошёл тест', notReached: 'Не дошли до этапа', notAsked: 'Не было вопроса',
    caveat: 'Здесь показаны только результаты этого прохождения. Количество и сложность вопросов различаются, поэтому это не рейтинг владения языками. Если выбирать наугад из четырёх вариантов, в среднем получится 25 % верных ответов. Пропуски отмечены отдельно от ошибок.',
    method: 'КАК УСТРОЕН ТЕСТ',
    methodBody: 'Начинаем с пяти простых слов на каждом языке. Если слова узнаются, переходим к пяти словам посложнее, а затем к десяти финальным: два простых, четыре средней сложности и четыре сложных. Языки, где всё пропущено, больше не появляются. Для каждого языка, прошедшего во второй этап, заранее оставляем вопросы на полный финал. Если все не помещаются в лимит, первыми идут языки с более сильным началом. Когда подходящих языков не остаётся, тест заканчивается. Если на язык не хватило лимита или вы закончили раньше, это не считается провалом.',
    scriptOn: 'С транслитерацией', scriptOff: 'Без транслитерации', restart: 'Пройти ещё раз', review: 'Все слова и ответы', yourAnswer: 'Ваш ответ', rightAnswer: 'Перевод',
    languageNames: { en: 'Английский', es: 'Испанский', fr: 'Французский', de: 'Немецкий', it: 'Итальянский', pt: 'Португальский', nl: 'Нидерландский', sv: 'Шведский', pl: 'Польский', ru: 'Русский', uk: 'Украинский', fi: 'Финский', el: 'Греческий', hy: 'Армянский', ka: 'Грузинский', ja: 'Японский', cs: 'Чешский', ro: 'Румынский', hu: 'Венгерский', da: 'Датский', no: 'Норвежский', tr: 'Турецкий' },
    familyNames: { Germanic: 'Германские языки', Romance: 'Романские языки', Slavic: 'Славянские языки', Uralic: 'Уральские языки', Hellenic: 'Греческая ветвь', Armenian: 'Армянская ветвь', Kartvelian: 'Картвельские языки', Japonic: 'Японо-рюкюские языки', Turkic: 'Тюркские языки' },
  },
};
